Index branch pull request
oscardelalanza/HTML-Froms pull request #1
Opened 2019-08-13 19:26 UTC by oscardelalanza

pull request on waiting for valitation by TSE

2019-08-14 00:37 UTC, Ispirett requested changes
Hey @oscardelalanza @bruna-genz   Great! job! with this project so far
![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 


* [ ] It has a Sign In button at the top right corner.

### to be Implemented 
It has a disclaimer text that matches the context and style of the original page.

There are just some things ti be implemented
##### Sign In Button

#### Footer
It contains copyright and addresses information.

### Also user this in your stickler.yml file  delete the rubocup file

  
linters:
   flake8:
  eslint:
    config: "./eslint.config"
  csslint:

2019-08-14 00:37 UTC, Ispirett commented on index.html
> +                    <input type="text" id="phone">
The type here should be type `type="tel"` not `type="text"`

2019-08-14 00:37 UTC, Ispirett commented on index.html
> +                <h2>Donec vel hendrerit dolor</h2>
### instead of this Lorem text please use the following 
 Title Create an Intuit account.

One account for everything Intuit, including Mint.

Learn More link.

2019-08-15 08:38 UTC, bolah2009 requested changes
## Awesome Job Team :muscle:

### The [clone](https://raw.githack.com/oscardelalanza/HTML-Froms/index/index.html) looks nice and used HTML Forms elements effectively. :100: 

### However, there are few chages to be made, see `REQUIRED` comments below.
- Add appropriate linter files (see [this comment](https://github.com/oscardelalanza/HTML-Froms/pull/1#discussion_r314209409))
- Add header content, images and icon (see [this comment](https://github.com/oscardelalanza/HTML-Froms/pull/1#discussion_r314213035))
- Align footer elements to the footer section of the page (see [this comment](https://github.com/oscardelalanza/HTML-Froms/pull/1#discussion_r314220221))

| Clone | Source Page |
| :-----: | :-----: |
| ![html form clone](https://user-images.githubusercontent.com/36057474/63082597-89a9e080-bf3e-11e9-82bb-e42f34e035bb.gif) | ![html form icons clone](https://user-images.githubusercontent.com/36057474/63082738-eb6a4a80-bf3e-11e9-9796-634a07fd8f6a.gif) |

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### Note that comments tagged `OPTIONAL` are strongly recommended but not required to approve the project.

2019-08-15 08:38 UTC, bolah2009 commented on .stickler.yml
> +    csslint:
`REQUIRED`

Are you using the right `.stickler.yml` config file, I am seeing `rubocop` which is a linter for `ruby` and `rails` projects. :thinking: 
Consider using this instead, :point_down: 
``` yml

linters:
  stylelint:
    config: 'stylelint.config.js'
```
See [here](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml) for `CSS stickler config file`.

Also, add the `stylelint.config.js` that was referenced above, this can be found [here](https://github.com/microverseinc/linters-config/blob/master/css/stylelint.config.js)
More details on setting up linter for HTML & CSS projects can be found [here](https://github.com/microverseinc/linters-config/tree/master/css)

2019-08-15 08:38 UTC, bolah2009 commented on index.html
> +        <a href="#">Sing In</a>
`OPTIONAL`

I think this is a typo, `Sign In` instead of `Sing In`? :thinking:

2019-08-15 08:38 UTC, bolah2009 commented on index.html
> +            <form>
`AWESOME` 

Nice job using `form` element, this makes the section represent a document section that contains interactive controls for submitting information to a web server. :+1:

2019-08-15 08:38 UTC, bolah2009 commented on index.html
> +    <main>
`AWESOME` 

Very good, using `main`, this shows the dominant content of the `<body>` of a document. More on `<main>` [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) :star2: :star:

2019-08-15 08:38 UTC, bolah2009 commented on index.html
> +<footer>
`AWESOME`

Very good job using `<footer>` element for the footer content, this helps to communicate meaning to the browser, developer, reader, and any other technologies interpreting the document (e.g. voice assistants). :ok_hand:

2019-08-15 08:38 UTC, bolah2009 commented on index.html
> +                    <input type="email" id="email" required>
`AWESOME`

Good job associating the `<label>` with an `<input>` element. :clap: :+1: 

> #### Associating a `<label>` with an `<input>` element offers some major advantages:
> 
> - The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
> 
> - You can click the associated label to focus/activate the input, as well as the input itself. This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.

Alternatively, you can nest the `<input>` directly inside the `<label>` like this: 

``` html
  <label for="email">Email address <br>
       <input type="email" name="email" id="email">
  </label> 
```


You can learn more [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

2019-08-15 08:38 UTC, bolah2009 commented on index.html
> +        <div class="container">
`REQUIRED`

The header image and icons seem to be missing.

| Source Page |
|:-----:|
|  ![html form icons source](https://user-images.githubusercontent.com/36057474/63075466-b6073200-bf29-11e9-9915-d2d8e495d501.png) |

2019-08-15 08:38 UTC, bolah2009 commented on css/styles.css
> +    height: 90vh;
`HINT`

Why are we using `height: 90vh; ` property here? This is affecting the `footer` element positioning.

| Clone Page when  `height: 90vh; ` is toggled with the dev tools |
|:-----:|
| ![html form footer-main clone](https://user-images.githubusercontent.com/36057474/63083218-199c5a00-bf40-11e9-95b6-fec8147bb515.gif)  |

2019-08-15 18:49 UTC, samgaco commented
### Hi @bruna-genz and @oscardelalanza :hand: 

### You have implemented all the changes requested diligently and everything looks perfect now! Hence, you are approved :muscle: Congratulations :+1: 

[OPTIONAL] You could work a bit more with the read me file, adding a live-demo of the site or finding inspiration in templates such as[ this one](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2).

### Anyways, congratulations again on the good work, hope you keep doing as great in your next projects :muscle: You can merge to the master branch now and submit the project completion form.

2019-08-15 19:02 UTC, merged